trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
  - job: SecondJob
    dependsOn: FirstJob
    steps:
    - bash: echo Build SecondJob

- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: DevDeployJob
    steps:
    - bash: echo DevDeployJob

- stage: QADeploy
  dependsOn: DevDeploy
  jobs:
  - job: QADeployJob
    steps:
    - bash: echo QADeployJob


- stage: ProdDeploy
  dependsOn: QADeploy
  jobs:
  - job: ProdDeployJob
    steps:
    - bash: echo ProdDeployJob

